--;;
DROP TRIGGER add_custom_field_to_entity_trig ON kaizen.custom_field;
--;;
DROP TRIGGER delete_custom_field_to_entity_trig ON kaizen.custom_field;
--;;
DROP FUNCTION kaizen.add_custom_field_to_entity;
--;;
DROP FUNCTION kaizen.delete_custom_field_to_entity;
--;;
DROP TABLE IF EXISTS kaizen.custom_field;
--;;
DROP VIEW IF EXISTS kaizen.ticket_view;
--;;
DROP TABLE IF EXISTS kaizen.ticket;
--;;
DROP TABLE IF EXISTS kaizen.status CASCADE;
--;;
DROP TABLE IF EXISTS kaizen.priority CASCADE;
--;;
