--;;
DROP TRIGGER add_custom_field_to_ticket_detail_trig ON kaizen.ticket_custom_field;
--;;
DROP TRIGGER delete_custom_field_to_ticket_detail_trig ON kaizen.ticket_custom_field;
--;;
DROP FUNCTION kaizen.add_custom_field_to_ticket_detail;
--;;
DROP FUNCTION kaizen.delete_custom_field_to_ticket_detail;
--;;
DROP TABLE kaizen.ticket_custom_field;
--;;
DROP VIEW kaizen.ticket;
--;;
DROP TABLE kaizen.ticket_detail;
--;;
DROP TABLE kaizen.ticket_status CASCADE;
--;;
DROP TABLE kaizen.ticket_priority CASCADE;
--;;
