DROP TABLE IF EXISTS kaizen.permission_rule CASCADE;
--;;
DROP TABLE IF EXISTS kaizen.permission_group CASCADE;
--;;
DROP TABLE IF EXISTS kaizen.permission_group_member CASCADE;
--;;
DROP TABLE IF EXISTS kaizen.permission_assignment CASCADE;
--;;
DROP TABLE IF EXISTS kaizen.permission_group_assignment CASCADE;
--;;
